apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: haproxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        tier: haproxy
    spec:
      containers:
      - name: haproxy
        image: haproxy:1.7.0-alpine
        ports:
        - containerPort: 80
        volumeMounts:
          - name: haproxy-config
            mountPath: /usr/local/etc/haproxy/haproxy.cfg
            subPath: haproxy.cfg
      - name: syslog-ng
        image: jefflaplante/syslog-ng:latest
        ports:
          - name: syslogudp
            containerPort: 514
            protocol: UDP 
          - name: syslogtcp
            containerPort: 601
      volumes:
      - name: haproxy-config
        configMap:
          name: haproxy
